



CREATE TABLE COMMUNITU
(
 "IP_PREFIX:" inet NOT NULL,
 "GEO_ID:"    integer NOT NULL,
 "VALUE1:"    integer(32) NOT NULL,
 "VALUE2:"    integer(32) NOT NULL DEFAULT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "IP_PREFIX:" ),
 CONSTRAINT FK_3_2 FOREIGN KEY ( "GEO_ID:" ) REFERENCES "GEO-TAB" ( GEO_ID )
);

CREATE INDEX FK_2 ON COMMUNITU
(
 "GEO_ID:"
);


-- ************************************** BGP

CREATE TABLE BGP
(
 "BGP_TAB_ID:"    integer NOT NULL,
 "TIMESTAMP:"     timestamp with time zone NOT NULL,
 "IP_PREFIX:"     inet NOT NULL,
 "PEER_IP_SRC:"   inet NOT NULL,
 "BGP_NEXTHOP:"   inet NOT NULL,
 "AS_PATH:"       jsonb NOT NULL,
 "PEER_TCP_PORT:" integer NOT NULL,
 "ORIGIN:"        varchar(1) NOT NULL,
 "EVENT_TYPE:"    varchar(10) NOT NULL,
 "AFI:"           integer NOT NULL,
 "SAFI:"          integer NOT NULL,
 "LOCAL_PREF:"    integer NOT NULL,
 "MED:"           integer NOT NULL,
 "SEQ:"           integer NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "BGP_TAB_ID:" ),
 CONSTRAINT FK_3_1 FOREIGN KEY ( "IP_PREFIX:" ) REFERENCES COMMUNITU ( "IP_PREFIX:" )
);

CREATE INDEX FK_3_1 ON BGP
(
 "IP_PREFIX:"
);

-- ************************************** "GEO-TAB"

CREATE TABLE "GEO-TAB"
(
 GEO_ID   integer NOT NULL,
 "COUNTRY:" varchar(50) NOT NULL,
 "CITY:"    varchar(50) NOT NULL,
 "GEOLOC:"  point NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( GEO_ID )
);



--proj model

-- Warning: You can generate script only for one table/view at a time in your Free plan 
-- 
-- ************************* SqlDBM: PostgreSQL *************************
-- * Generated by SqlDBM: first_proj_v2, v26 by ilyakleyn2000@gmail.com *



-- ************************************** "AS-SET"

CREATE TABLE "AS-SET"
(
 "as-set:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 "parent-as-set:" varchar(10) NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "as-set:" ),
 CONSTRAINT FK_1 FOREIGN KEY ( "parent-as-set:" ) REFERENCES "AS-SET" ( "as-set:" )
);

CREATE INDEX FK_2 ON "AS-SET"
(
 "parent-as-set:"
);



-- ************************************** "AUT-NUM"

CREATE TABLE "AUT-NUM"
(
 "aut-num:"       varchar(10) NOT NULL DEFAULT not in (0, 65535) and (not between 64496 and 64511 ),
 "as-name:"       varchar(50) NOT NULL,
 "member-of:"     varchar(10) NULL,
 "import:"        jsonb NULL,
 "export:"        jsonb NULL,
 "org:"           varchar(50) NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "status:"        varchar(20) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "aut-num:" ),
 CONSTRAINT FK_2 FOREIGN KEY ( "member-of:" ) REFERENCES "AS-SET" ( "as-set:" ),
 CONSTRAINT check_for_reserved1 CHECK ( "aut-num:" not in (0, 65535) ),
 CONSTRAINT check_for_reserved2 CHECK ( "aut-num:" not between 64496 and 64511 )
);

CREATE INDEX FK_2 ON "AUT-NUM"
(
 "member-of:"
);

CREATE INDEX Index_on_aut_name ON "AUT-NUM" USING btree
(
 "as-name:"
);

CREATE INDEX "Index_on_aut-num" ON "AUT-NUM" USING btree
(
 "aut-num:"
);

CREATE INDEX Index_on_org ON "AUT-NUM" USING btree
(
 "org:"
);



-- ************************************** INETNUM

CREATE TABLE INETNUM
(
 "inetnum:"       inet NOT NULL,
 "netname:"       varchar(50) NOT NULL,
 "country:"       varchar(50) NOT NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "status:"        varchar(20) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "inetnum:" )
);

CREATE INDEX Index_on_inetnum ON INETNUM USING gin
(
 "inetnum:"
);

CREATE INDEX Index_on_netname ON INETNUM USING btree
(
 "netname:"
);



-- ************************************** INETNUM6

CREATE TABLE INETNUM6
(
 "inet6num:"      inet NOT NULL,
 "netname:"       varchar(50) NOT NULL,
 "country:"       varchar(50) NOT NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "status:"        varchar(20) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "inet6num:" )
);


-- ************************************** ROUTE

CREATE TABLE ROUTE
(
 "route:"         inet NOT NULL,
 "origin:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NULL,
 "inetnum:"       inet NOT NULL,
 "member-of:"     varchar(10) NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "route:", "origin:" ),
 CONSTRAINT FK_3 FOREIGN KEY ( "origin:" ) REFERENCES "AUT-NUM" ( "aut-num:" ),
 CONSTRAINT FK_4 FOREIGN KEY ( "inetnum:" ) REFERENCES INETNUM ( "inetnum:" ),
 CONSTRAINT route_gre_or_eq_inetnum CHECK ( "route:" >= "inetnum:" )
);

CREATE INDEX FK_2 ON ROUTE
(
 "origin:"
);

CREATE INDEX FK_3 ON ROUTE
(
 "inetnum:"
);


-- ************************************** ROUTE6

CREATE TABLE ROUTE6
(
 "route6:"        inet NOT NULL,
 "origin:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NULL,
 "inet6num:"      inet NOT NULL,
 "member-of:"     varchar(10) NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "route6:", "origin:" ),
 CONSTRAINT FK_5 FOREIGN KEY ( "inet6num:" ) REFERENCES INETNUM6 ( "inet6num:" ),
 CONSTRAINT FK_6 FOREIGN KEY ( "origin:" ) REFERENCES "AUT-NUM" ( "aut-num:" ),
 CONSTRAINT route6_gre_or_eq_inet6num CHECK ( "route6:">="inet6num:" )
);

CREATE INDEX FK_2 ON ROUTE6
(
 "inet6num:"
);

CREATE INDEX FK_3 ON ROUTE6
(
 "origin:"
);


--in right order 


-- ************************************** INETNUM6

CREATE TABLE INETNUM6
(
 "inet6num:"      inet NOT NULL,
 "netname:"       varchar(50) NOT NULL,
 "country:"       varchar(50) NOT NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "status:"        varchar(20) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "inet6num:" )
);


-- ************************************** INETNUM

CREATE TABLE INETNUM
(
 "inetnum:"       inet NOT NULL,
 "netname:"       varchar(50) NOT NULL,
 "country:"       varchar(50) NOT NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "status:"        varchar(20) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "inetnum:" )
);

CREATE INDEX Index_on_inetnum ON INETNUM USING gin
(
 "inetnum:"
);

CREATE INDEX Index_on_netname ON INETNUM USING btree
(
 "netname:"
);


-- ************************************** "AS-SET"

CREATE TABLE "AS-SET"
(
 "as-set:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 "parent-as-set:" varchar(10) NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "as-set:" ),
 CONSTRAINT FK_1 FOREIGN KEY ( "parent-as-set:" ) REFERENCES "AS-SET" ( "as-set:" )
);

CREATE INDEX FK_2 ON "AS-SET"
(
 "parent-as-set:"
);



-- ************************************** ROUTE

CREATE TABLE ROUTE
(
 "route:"         inet NOT NULL,
 "origin:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NULL,
 "inetnum:"       inet NOT NULL,
 "member-of:"     varchar(10) NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "route:", "origin:" ),
 CONSTRAINT FK_3 FOREIGN KEY ( "origin:" ) REFERENCES "AUT-NUM" ( "aut-num:" ),
 CONSTRAINT FK_4 FOREIGN KEY ( "inetnum:" ) REFERENCES INETNUM ( "inetnum:" ),
 CONSTRAINT route_gre_or_eq_inetnum CHECK ( "route:" >= "inetnum:" )
);

CREATE INDEX FK_2 ON ROUTE
(
 "origin:"
);

CREATE INDEX FK_3 ON ROUTE
(
 "inetnum:"
);


-- ************************************** ROUTE6

CREATE TABLE ROUTE6
(
 "route6:"        inet NOT NULL,
 "origin:"        varchar(10) NOT NULL,
 "org:"           varchar(50) NULL,
 "inet6num:"      inet NOT NULL,
 "member-of:"     varchar(10) NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "route6:", "origin:" ),
 CONSTRAINT FK_5 FOREIGN KEY ( "inet6num:" ) REFERENCES INETNUM6 ( "inet6num:" ),
 CONSTRAINT FK_6 FOREIGN KEY ( "origin:" ) REFERENCES "AUT-NUM" ( "aut-num:" ),
 CONSTRAINT route6_gre_or_eq_inet6num CHECK ( "route6:">="inet6num:" )
);

CREATE INDEX FK_2 ON ROUTE6
(
 "inet6num:"
);

CREATE INDEX FK_3 ON ROUTE6
(
 "origin:"
);

-- ************************************** "AUT-NUM"

CREATE TABLE "AUT-NUM"
(
 "aut-num:"       varchar(10) NOT NULL DEFAULT not in (0, 65535) and (not between 64496 and 64511 ),
 "as-name:"       varchar(50) NOT NULL,
 "member-of:"     varchar(10) NULL,
 "import:"        jsonb NULL,
 "export:"        jsonb NULL,
 "org:"           varchar(50) NULL,
 "admin-c:"       varchar(50) NOT NULL,
 "tech-c:"        varchar(50) NOT NULL,
 "status:"        varchar(20) NOT NULL,
 "mnt-by:"        jsonb NOT NULL,
 "created:"       timestamp with time zone NOT NULL,
 "last-modified:" timestamp with time zone NOT NULL,
 "source:"        varchar(10) NOT NULL,
 CONSTRAINT PK_1 PRIMARY KEY ( "aut-num:" ),
 CONSTRAINT FK_2 FOREIGN KEY ( "member-of:" ) REFERENCES "AS-SET" ( "as-set:" ),
 CONSTRAINT check_for_reserved1 CHECK ( "aut-num:" not in (0, 65535) ),
 CONSTRAINT check_for_reserved2 CHECK ( "aut-num:" not between 64496 and 64511 )
);

CREATE INDEX FK_2 ON "AUT-NUM"
(
 "member-of:"
);

CREATE INDEX Index_on_aut_name ON "AUT-NUM" USING btree
(
 "as-name:"
);

CREATE INDEX "Index_on_aut-num" ON "AUT-NUM" USING btree
(
 "aut-num:"
);

CREATE INDEX Index_on_org ON "AUT-NUM" USING btree
(
 "org:"
);
